version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
