[package]
name = "cheapskate-ci"
edition = "2018"
version = "0.1.6"
authors = ["Max Jacobson <max@hardscrabble.net>"]
readme = "README.md"
description = "CLI for those who are too cheap to pay for CI but still want required GitHub status checks. Now they can run this locally."
license = "MIT"
repository = "https://github.com/maxjacobson/cheapskate-ci"
keywords = ["ci"]

[dependencies]
clap = "2.33.3"
env_logger = "0.9.3"
log = "0.4.11"
psst = "0.1"
reqwest = "0.9"
toml = "0.5"
